### ISSUE TITLE
max letters

### ISSUE THREAD

**Issue by 12345qert** [VulcanWM/what-if-nextjs#39]
it says max number of chars is 300 but when u submit more than 100 it says: Your thoughts have to be less than 100 characters!
in: https://what-if-scenarios.vercel.app/scenario/7

**Comment by VulcanWM** [comment]
thanks! i'll work on this.
what's your replit username?

**Comment by VulcanWM** [comment]
so the function checked if the length was over 300 or not, but then if it was, it would output that it was longer than 100
