### ISSUE TITLE
No Empty Response Check

### ISSUE THREAD

**Issue by JustinBoverhof** [VulcanWM/what-if-nextjs#43]
This is more of a preference than a bug but it allows submission of just spaces as well as no characters at all. AKA empty responses

**Comment by VulcanWM** [comment]
oh yea, good catch!
what's your replit username?

**Comment by Raadsl** [comment]
Didn't want to make a new issue since it's kind of the same but, you can submit a new scenario with only a title, and an empty description. I think that also shouldn't be possible

**Comment by VulcanWM** [comment]
oh yea, i forgot about that.
thanks for reminding me!
will work on that

**Comment by VulcanWM** [comment]
- [x] empty response check for thought comment (trim spaces)
- [x] empty response check for description on scenario (trim spaces)
- [x] empty response check for title on scenario (trim spaces)

**Comment by JustinBoverhof** [comment]
my replit is @Justin83B
