### ISSUE TITLE
No submission cooldown or limit

### ISSUE THREAD

**Issue by JustinBoverhof** [VulcanWM/what-if-nextjs#44]
As far as I can tell no cap or cooldown on submission of prompts could allow for spam

**Comment by VulcanWM** [comment]
as in a cooldown for the amount of scenarios you can comment on?

**Comment by JustinBoverhof** [comment]
As far as I can tell I can suggest an infinite amount of scenarios for the admin to approve this could lead to spam on your end. Once again more of a preference than a bug but one to consider

**Comment by VulcanWM** [comment]
there's a limit of 5 unverified scenarios i'm pretty sure.
does that not work?

**Comment by VulcanWM** [comment]
just checked it out, it says that the limit is 5, but the cooldown only works after 6.
fixed that
