### ISSUE TITLE
Dashboard and Your Profile both lead to dashboard

### ISSUE THREAD

**Issue by JustinBoverhof** [VulcanWM/what-if-nextjs#46]
when clicked both buttons lead to the same place

**Comment by VulcanWM** [comment]
hey, i cant seem to be able to reproduce this error.

**Comment by JustinBoverhof** [comment]
If I click on the new scenario tab then click on the your profile tab I am taken to the dashboard. so the profile tab leads to https://what-if-scenarios.vercel.app/dashboard and if you click on the profile tab while on the dashboard nothing happens.

**Comment by VulcanWM** [comment]
that doesn't seem to be happening to me.
also the navbar on all the pages have the same code so i'm not sure why only you are having that problem
