### ISSUE TITLE
Length Typo Bug

### ISSUE THREAD

**Issue by Immortal-Fig** [VulcanWM/what-if-nextjs#47]
<img width="538" alt="Screenshot 2023-07-24 at 9 59 16 PM" src="https://github.com/VulcanWM/what-if/assets/86179431/82f61239-e067-4e7d-9fd2-cc732505982c">

"less than 100"

"less than 300"

replit: @ImmortalFigFig

**Comment by VulcanWM** [comment]
same as #39
