### ISSUE TITLE
Bug: If you specify some html tags in your username, you cannot view your profile correctly.

### ISSUE THREAD

**Issue by arandomuserwouldbefine** [VulcanWM/what-if-nextjs#49]
Hello, I created a username with the value of a weird html code and when I visit my profile I get 404 not found.

**Comment by VulcanWM** [comment]
good catch!

**Comment by VulcanWM** [comment]
what's your replit username?

**Comment by VulcanWM** [comment]
*NOTE TO SELF:*

Try using this: https://www.geeksforgeeks.org/how-to-strip-out-html-tags-from-a-string-using-javascript/

**Comment by arandomuserwouldbefine** [comment]
Am i applicable for any bounty? Here's my replit username: @custombana010

**Comment by arandomuserwouldbefine** [comment]
Hey, any update regarding my bug finding?

**Comment by VulcanWM** [comment]
tipped, hope you enjoy your 1k cycles!
didnt get a chance to work on this yesterday, will today

**Comment by arandomuserwouldbefine** [comment]
Sorry but, I dont see that I received 1k cycles.

**Comment by arandomuserwouldbefine** [comment]
Can you accept my bounty so that I get that dollar amount and cycles? I am pretty new to replit so dont know much about it.

**Comment by VulcanWM** [comment]
> Can you accept my bounty so that I get that dollar amount and cycles? I am pretty new to replit so dont know much about it.

I tipped one of your repls: https://replit.com/@custombana010/DiscordBot?v=1

**Comment by VulcanWM** [comment]
deleted your account, can you try recreating your account with the same username and see if it removes the html tags

**Comment by VulcanWM** [comment]
@arandomuserwouldbefine reopen this issue if you still can create usernames with tags in them
